[package]
name = "kova-render"
description = "GPU scene renderer for Kova (wgpu)."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
kova-core.workspace = true
wgpu.workspace = true
bytemuck.workspace = true
etagere.workspace = true
log.workspace = true
rustc-hash.workspace = true
pollster.workspace = true
kova-text.workspace = true
