[package]
name = "kova-native-platform"
description = "Windowing, event loop and OS integration for Kova Native."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
include.workspace = true
publish.workspace = true
documentation = "https://docs.rs/kova-native-platform"

[dependencies]
kova-native-core.workspace = true
kova-native-input.workspace = true
winit.workspace = true
arboard.workspace = true
log.workspace = true
